// <auto-generated />
namespace Wiz.Gringotts.UIWeb.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddParentChildrenToBatch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddParentChildrenToBatch));
        
        string IMigrationMetadata.Id
        {
            get { return "201512152031053_AddParentChildrenToBatch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
