// <auto-generated />
namespace DSHS.WA.LocalFunds.UIWeb.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddNaughtyFlagToClient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNaughtyFlagToClient));
        
        string IMigrationMetadata.Id
        {
            get { return "201601132116073_AddNaughtyFlagToClient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
